travis:
  secure:
    BINSTAR_TOKEN: coxb4j97ySAWyShVYJftx0y12DzN2O2xKr9zSyJhcIdeyrHMPL3iqg7YoKJL6ye7LagOsBmoXEQo7IRBq7Gn6+TzXSbkSnKq4MXvJgN5ftGkX16hMzmchg3Rp/ZUw8HIbxPmscQwmgE25Q2DUhRoRtaEvjCzm3y8uNkEiKQTF9yQXI4vrtwPyvuvJXOEFOYse/q6+CmwoMzf/LqrAjeyxSBZW28d8R3R1L+4UjDrX12XUcVx6u/cqy6EBYYFe0fo/nHiEUQ3HkrVB3q6G7dFw9aPLlArsPokDF8oNMfwOm07X/xP85L4BiM2W3WfDbwfeYHH7QRUnCF0es9Z9WybOX/YJpzDAogMM+D8YvSF/Faqgn95NxUWJVvz8Y6xJkhvEgqt8p+5IhT0oK2IBEC0+xgBshDucYirNjVkhXlKjPAaypAUJ3n0E7D3Psa7FqjykwggL9RarO83uDk0oAiQVvahYcqjE/FnYEI/6IhJiAmffkX+QYjJR37erEAvDWxM39Oj6Ehl11yxb9FHLiTkvDzyJu6fwybJXteJ+hIijEEx1Kf4UzP44YoyChJKnSPCwBSDqBlCjXwHfuHjUu3Y59Y0VguHXiXbqWPrHaRB6XSLultIgnzF2w4S+ziw8gCy4FNFPbBMD1kSp9fC+nrshRqOPn/xxaLv0/QOb9J0z9s=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
